name: Deploy

on:
  push:
    branches:
      - main

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
  release:
    uses: ./.github/workflows/release.yml
    needs: validate
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
