name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn semantic-release
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}